name: Sarre Brand UI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: CheckoutComponent source code
        uses: actions/checkout@v3

      # Log into dockerhub
      - name: Log into DockerHub
        uses: docker/login-action@v3
        with:
          username: emmanuelu17
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # See  https://buildpacks.io/docs/buildpack-author-guide/publishing-with-github-actions/
      - name: Setup-tools
        uses: buildpacks/github-actions/setup-tools@v5.1.0

      - name: Setup pack
        uses: buildpacks/github-actions/setup-pack@v5.1.0

      # See more on paketo web servers https://github.com/paketo-buildpacks/web-servers
      # See for more on nginx config https://docs.vmware.com/en/VMware-Tanzu-Buildpacks/services/tanzu-buildpacks/GUID-nginx-nginx-buildpack.html
      - name: Build image
        run: |
          #!/usr/bin/env bash
          pack config default-builder paketobuildpacks/builder:base
          pack build emmanuelu17/sarrebrand --buildpack paketo-buildpacks/web-servers \
          --env "BP_WEB_SERVER=nginx" \
          --env "BP_WEB_SERVER_ROOT=dist/sarrebrand" \
          --env "BP_WEB_SERVER_ENABLE_PUSH_STATE=true" \
          --env "NODE_ENV=production"
        shell: bash

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v3

      - name: Tag & Publish to Docker Hub
        run: |
          #!/usr/bin/env bash
          docker push --all-tags emmanuelu17/sarrebrand
        shell: bash
        env:
          IMAGE_NAME: ${{ secrets.APP_IMAGE }}
